services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: giftilist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: giftilist-rabbitmq
    ports:
      - "5672:5672"     # app connection
      - "15672:15672"   # management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
  pgdata:
