services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: giftilist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
