name: backend-ci

on:
  push:
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend.yml'

permissions:
  contents: read

concurrency:
  group: backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew test --stacktrace
        env:
          SPRING_PROFILES_ACTIVE: test
